apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    app: my-web-app
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30005 #any port between 30000 and 32767
    
