on:
    push:
        branches:
            - master






jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout
              uses: actions/checkout@v4.1.1
             
            - name: "Login to DockerHub"
              run: docker login --username $ {{ secrets.DOCKER_USERNAME }} --password $ {{ secrets.DOCKER_TOKEN}}


           
            