on:
    push:
        branches:
            - master






jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: $ {{ secrets.DOCKER_USERNAME }}
                password: $ {{ secrets.DOCKER_TOKEN }}
                logout: false
              

           
            