on:
    push:
        branches:
            - master






jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3
            with:
                fetch-depth: 0
          - name: "login to docker"
            run: docker login --username $ {{secrete.DOCKER_USERNAME}} --password $ {{secrets.DOCKER_TOKEN}}


             
           


           
            