on:
    push:
        branches:
            - master






jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              

            - name: "Bulding docker image"
              run: docker build -t $ {{ secrets.DOCKER_USERNAME}}/jury .

            - name: "Building docker image"
              run: docker push $ {{ sectets.DOCKER_USERNAME }}/jury
            